const BULK_INSERT_LIMIT = 500
const CART_SESSION_MINUTE_TIME_LIMIT = 10
const BOOK_CHECKOUT_NUM_DAYS = 14

module.exports = {
	BULK_INSERT_LIMIT,
	CART_SESSION_MINUTE_TIME_LIMIT,
	BOOK_CHECKOUT_NUM_DAYS
}